### ISSUE TITLE
Default source for FreeBSD

### ISSUE THREAD

**Issue by awildpatchappears** [purplehazech/puppet-syslogng#8]
Would you please make 

    source src {
      unix-dgram("/var/run/log");
      unix-dgram("/var/run/logpriv" perm(0600));
      internal(); file("/dev/klog");
    };

the default source ('s_log') for FreeBSD jails?

(http://lists.freebsd.org/pipermail/freebsd-bugs/2013-June/053062.html)

I understand that you're (re-)using the SCL repository. Therefore I wrote an alternative source:

```
# -- files/scl/syslog-ng.conf.d/source.d/freebsd_jail_default.conf

##
# Default source for FreeBSD jails
#
# Conflicts with default.conf
#
source s_log {
  unix-dgram("/var/run/log");
  unix-dgram("/var/run/logpriv" perm(0600));
  internal(); file("/dev/klog");
};
```

**Comment by hairmare** [comment]
I switched to using a local (to this repo) copy of default.conf for FreeBSD.

Has been released to the puppet module forge as 0.6.0.

Please open issues if you find anything else you need.
